# Serve the development server
# docker compose -f docker-compose-build.yml up
services:
  jekyll:
    command: jekyll serve
    image: jekyll/jekyll:3.8.6
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/app/vendor/bundle:/usr/local/bundle"
#    environment:
#      JEKYLL_UID: 1001
#      JEKYLL_GID: 1001
    ports:
      - "4000:4000"
      - "35731:35729"
      - "3000:3000"
    networks:
      - default